### ISSUE TITLE
Update the matches url pattern

### ISSUE THREAD

**Issue by nobe4** [npny/mdn-automatic-translation#2]
When you start editing, you save your changes and you go back to them after, the url does not match with the current one. e.g. `https://developer.mozilla.org/fr/docs/Web/API/ExtendableEvent$edit`

We should have a double verification for the translation possibility: urls and html elements, to confirm.
I see the `details#trans-content` in the markup translation pages, we could add the edit url to the matches and add a new rule in the start checks.

**Comment by npny** [comment]
Merged into master
